name: "Formatting queries"
on: # rebuild any PRs and master branch changes
    pull_request:
    push:
        branches:
            - master
            
permissions:
    contents: write
    
jobs:
    test: # make sure the action works on a clean machine without building
        name: Run auto formatter
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Install zetasql
              run: |
                wget https://github.com/Matts966/zetasql-formatter/releases/download/v1.6.5/zetasql-formatter_linux_x86_64.zip
                sudo unzip zetasql-formatter_linux_x86_64.zip -d /usr/local/bin
                rm zetasql-formatter_linux_x86_64.zip

            - name: SQLAutoFormatter
              uses: yoheikikuta/sql-autoformat-action@v1.0.2
              with:
                github_token: ${{ secrets.github_token }}
